### ISSUE TITLE
Firewall occasionally not adding

### ISSUE THREAD

**Issue by rocketiscool** [adnanjaw/ip-whitelist-on-hetznerfw#2]
Sometimes in a parallel job, one of the firewalls aren't added resulting in my whole job causing an error and having to be re-ran manually.

Any idea why?

**Comment by adnanjaw** [comment]
Hey @rocketiscool 

Are you adding a completely new firewall, or creating it manually first and then using it in the action? this action does not create a new firewall automatically; you will need to provide the name of an existing firewall for it to function correctly.

Please see the documentation hier: [docs]( https://adnanjaw.github.io/ip-whitelist-on-hetznerfw/)

> ⚠️ **Caution**  
> 
> When the **cleanup** option is enabled, **all rules** in the specified firewall will be deleted **after the action runs**.
> If you are using an **existing firewall**, ensure it does not contain any critical rules before proceeding, as they will be **permanently removed**.
> For safe usage, it is recommended to create and use a **dedicated firewall** for this action to avoid accidental deletion of other important rules.


Let me know if that helps?

**Comment by adnanjaw** [comment]
@rocketiscool are you still experiencing the same issue? If yes, please show me what is your workflow doing!

**Comment by rocketiscool** [comment]
Sorry didnt see your reply.

I have created the firewall, but when parallel jobs run theres a 1 in 3 chance that one of my jobs will fail due to the hetzner firewall not updating one of the jobs firewalls

```
name: Deploy Web and Team Apps

on:
  push:
    branches:
      - staging
      - production  # Deploy when changes are pushed to the staging or production branches

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Get the public IP of the runner using curl and jq
      - name: Get IP Addresses
        id: ip
        uses: haythem/public-ip@v1.3
      
      # Step 3: Whitelist runner IP on Hetzner firewall
      - name: Whitelist runner IP on Hetzner firewall
        uses: adnanjaw/ip-whitelist-on-hetznerfw@v2
        with:
          hetzner_api_key: ${{ secrets.HETZNER_API_KEY }}
          ip_address: ${{ steps.ip.outputs.ipv4 }}
          firewall_name: Github Actions for PGSQL
          direction: in
          protocol: tcp
          port: 5432

  build-team:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Get the public IP of the runner using curl and jq
      - name: Get IP Addresses
        id: ip
        uses: haythem/public-ip@v1.3
      
      # Step 3: Whitelist runner IP on Hetzner firewall
      - name: Whitelist runner IP on Hetzner firewall
        uses: adnanjaw/ip-whitelist-on-hetznerfw@v2
        with:
          hetzner_api_key: ${{ secrets.HETZNER_API_KEY }}
          ip_address: ${{ steps.ip.outputs.ipv4 }}
          firewall_name: Github Actions for PGSQL
          direction: in
          protocol: tcp
          port: 5432
```
